language: ruby
rvm: 2.3

# User container based travis infrastructure which allows caching
# features for open source projects.
sudo: false
cache: bundler

services:
  - redis-server
  - mysql

script:
  - bin/rspec
